---
abstract: 'automatically extract Perl::Critic policy prereqs'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::MockModule: '0.14'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-AutoPrereqs-Perl-Critic
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  CPAN::Meta::YAML: '0'
  CPAN::Version: '0'
  Dist::Zilla::Role::PrereqSource: '0'
  HTTP::Tiny: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  Path::Tiny: '0'
  Perl::Critic: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Dist-Zilla-Plugin-AutoPrereqs-Perl-Critic/issues
  homepage: https://github.com/skirmess/Dist-Zilla-Plugin-AutoPrereqs-Perl-Critic
  repository: https://github.com/skirmess/Dist-Zilla-Plugin-AutoPrereqs-Perl-Critic.git
version: '0.006'
